name: Build and Push Docker Image

on:
  workflow_dispatch:  # 手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      # 第一步：检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 第二步：设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 第三步：登录 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 第四步：构建并推送 Docker 镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .  # 设置构建上下文为当前目录
          file: ./Dockerfile  # 使用 Dockerfile 构建镜像
          push: true  # 推送镜像到 Docker Hub
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/grok2api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/grok2api:${{ github.sha }}
